# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1e167b91c80199a018248959ada4172f6162f4c9c93c3db26bb6e1f6983d4fe3300173d36fef66f0588994e9cd499bfce3c14a5d799ea2d26509a0920259de4a

test:
  secret_key_base: 776500be427ebb460b067a1bb4820b9132801c4d865938444b54d5a9fbf34d80f38662d47a39233bf71a71eb7fa65f51428e4a37ff918d01dd9c1e4943b55178

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
